# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/kgopal/Downloads/lab8_elevator_control/lab8_elevator_control.cache/wt [current_project]
set_property parent.project_path /home/kgopal/Downloads/lab8_elevator_control/lab8_elevator_control.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo /home/kgopal/Downloads/lab8_elevator_control/lab8_elevator_control.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  /home/kgopal/Downloads/lab8_elevator_control/lab8_elevator_control.srcs/sources_1/imports/Lab8/v_to_cathode_char.vhd
  /home/kgopal/Downloads/lab8_elevator_control/lab8_elevator_control.srcs/sources_1/imports/Lab8/v_to_cathode_num.vhd
  /home/kgopal/Downloads/lab8_elevator_control/lab8_elevator_control.srcs/sources_1/imports/Lab8/display.vhd
  /home/kgopal/Downloads/lab8_elevator_control/lab8_elevator_control.srcs/sources_1/imports/Lab8/ringer.vhd
  /home/kgopal/Downloads/lab8_elevator_control/lab8_elevator_control.srcs/sources_1/imports/Lab8/pulse1.vhd
  /home/kgopal/Downloads/lab8_elevator_control/lab8_elevator_control.srcs/sources_1/imports/Lab8/pulse.vhd
  /home/kgopal/Downloads/lab8_elevator_control/lab8_elevator_control.srcs/sources_1/imports/Lab8/ten_clock.vhd
  /home/kgopal/Downloads/lab8_elevator_control/lab8_elevator_control.srcs/sources_1/imports/Lab8/display_clock.vhd
  /home/kgopal/Downloads/lab8_elevator_control/lab8_elevator_control.srcs/sources_1/imports/Lab8/request_handler.vhd
  /home/kgopal/Downloads/lab8_elevator_control/lab8_elevator_control.srcs/sources_1/imports/Lab8/status_display_block.vhd
  /home/kgopal/Downloads/lab8_elevator_control/lab8_elevator_control.srcs/sources_1/imports/Lab8/lift_controller.vhd
  /home/kgopal/Downloads/lab8_elevator_control/lab8_elevator_control.srcs/sources_1/imports/Lab8/lab8_elevator_control.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/kgopal/Downloads/lab8_elevator_control/lab8_elevator_control.srcs/constrs_1/imports/Desktop/lab8_elevator_control.xdc
set_property used_in_implementation false [get_files /home/kgopal/Downloads/lab8_elevator_control/lab8_elevator_control.srcs/constrs_1/imports/Desktop/lab8_elevator_control.xdc]


synth_design -top lab8_elevator_control -part xc7a35tcpg236-1


write_checkpoint -force -noxdef lab8_elevator_control.dcp

catch { report_utilization -file lab8_elevator_control_utilization_synth.rpt -pb lab8_elevator_control_utilization_synth.pb }
